### PR TITLE
hard code locale

### PR DESCRIPTION
**Pull request by jrobiche**
The [Locale Page](https://www.xbox.com/en-US/Shell/ChangeLocale) on xbox.com has been updated, resulting in the locale id no longer existing in the HTML.

At this time, the ids and names for all of the locales exist in the javascript file at [https://assets-www.xbox.com/xbox-web/static/js/LocalePickerPage.7c45fcf5.chunk.js](https://assets-www.xbox.com/xbox-web/static/js/LocalePickerPage.7c45fcf5.chunk.js) which is used when the [Locale Page](https://www.xbox.com/en-US/Shell/ChangeLocale) is rendered.

I do not think that parsing the javascript file would be a maintainable solution because the url will change anytime that the file changes.

I wanted to get feedback on whether or not hard coding the locales would be a good solution, so I have only added `en-US` for now. If hard coding the locales is an ok solution, then I will add all of the other locales to the file.

### CODE REVIEW

**Comment by KiwiMeowree** [comment]
Was going to say. As I started to make indie covers for the titles that are missing & noticed that AAE wouldn't pull from xbox com yesterday. Was about to dm you but seems your already looked into it.

**Comment by jrobiche** [comment]
> Was going to say. As I started to make indie covers for the titles that are missing & noticed that AAE wouldn't pull from xbox com yesterday. Was about to dm you but seems your already looked into it.

The timing was crazy. I did not have my computer setup for a while until last week. Then last night I randomly decided to check RMS and there was a post about it not working :smile:

**Comment by KiwiMeowree** [comment]
Yeah Microsoft done some changed apparently. As people having issues getting there live accounts to download to there 360 retail or modded. Most people can download them but then some still can't. It's Still an issue. By knowing this I should of assumed AAE wouldn't work because of these new changes

**Comment by Swizzy** [comment]
@jrobiche are you willing to add all the available locales as of right now?

**Comment by jrobiche** [comment]
In case this might be useful in the future, here is a python script that can parse the locales from the javascript file mentioned above.

```python
import re
import requests


def parse_locales(file_data):
    locales = []
    for locale_name, locale_var in re.findall(
        r'{title:"([^"]+)",locale:([^}]+)}', file_data.decode("utf-8")
    ):
        locale_id = f"{locale_var[2:4]}-{locale_var[4:]}"
        locales.append((locale_id, locale_name))
    return locales


def main():
    url = "https://assets-www.xbox.com/xbox-web/static/js/LocalePickerPage.7c45fcf5.chunk.js"
    resp = requests.get(url, timeout=60)
    resp.raise_for_status()
    for locale_id, locale_name in parse_locales(resp.content):
        print(f'ret.Add(new XboxLocale("{locale_id}", "{locale_name}"));')


if __name__ == "__main__":
    main()
```

**Comment by jrobiche** [comment]
> @jrobiche are you willing to add all the available locales as of right now?

Commit updated to include all locales and added a new commit to increase version from 1.3.2.0 to 1.3.3.0

**Comment by KiwiMeowree** [comment]
Thank you @jrobiche & @Swizzy. Works like a charm appreciate it man

**Pull request merged**
